import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsCapstone: SidebarsConfig = {
  capstoneSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsCapstone;