import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsCourse: SidebarsConfig = {
  courseSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsCourse;